### ISSUE TITLE
Figma mislabeled as 1st entry for IrfanView

### ISSUE THREAD

**Issue by wjhill** [mariosemes/Chocolater#1]
Hi! You have two entries in "Photo & Image" labeled IrfanView. The 1st one, however, appears to actually be for Figma:
![figma-mislabel](https://user-images.githubusercontent.com/70453/113577307-08a9cc00-95ef-11eb-849b-de2918cdd533.jpg)

**Comment by mariosemes** [comment]
Ty. Typo fixed and pushed.
