### ISSUE TITLE
Logitech Gaming Software 

### ISSUE THREAD

**Issue by gabriel-vanca** [mariosemes/Chocolater#2]
This is the old Logitech software that does not support new hardware. The current Logitech software (called Logitech G Hub) is not on chocolatey. Probably better to remove it so as to avoid confusion. 

(Or, if you could add the G Hub to the community repositories, that would be amazing.)

**Comment by mariosemes** [comment]
Thanks for the feedback.
Logitech removed. There is no G HUB currently in the community repo as you mentioned.
