### ISSUE TITLE
Please add microsoft's runtimes (directx, .net framework and visual c++ runtimes)

### ISSUE THREAD

**Issue by pitsi** [mariosemes/Chocolater#3]
**App name:** 
Directx, .net framework and visual c++ runtimes

**Chocolatey URLs:** 
https://community.chocolatey.org/packages/directx
https://community.chocolatey.org/packages/dotnetfx
https://community.chocolatey.org/packages/vcredist-all

**Category:** 
Microsoft's runtimes?

Keep in mind that chocolatey offers different packages for every single vcredist (vcredist2005, vcredist2008, and so on) and .net framework version (dotnet3.5, dotnet4.7 and so on). 
The vcredist-all package installs all the vcredist* packages starting from vcredist2005. The dotnetfx package however installs only the latest stable version of .net framework, i.e 4.8 at the time of writing.

**Comment by mariosemes** [comment]
Added with the latest commit.
